[package]
name = "ili9488"
version = "0.1.0"
authors = ["Jan Szumiec <jan.szumiec@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
